### ISSUE TITLE
lint-staged & husky 확인

### ISSUE THREAD

**Issue by minjongbaek** [prgrms-fe-devcourse/FEDC3_DigDigDeep_Yuri#241]
## 📃 작업 내용

lint-staged & husky 가 정상적으로 작동하는지 확인합니다.

**Comment by minjongbaek** [comment]
@mxx-kor @fly1chop @dazzel3 

내용 확인해주세요!

별다른 피드백이 없다면 내일 이슈 닫도록 하겠습니다!

**Comment by dazzel3** [comment]
@minjongbaek 오늘 집가서 테스트 해보겠습니당!!

**Comment by mxx-kor** [comment]
<img width="388" alt="스크린샷 2023-02-09 오후 2 23 23" src="https://user-images.githubusercontent.com/82329983/217725498-2ce4d358-d906-4bae-9b20-a3f229b07fba.png">
헉..

**Comment by minjongbaek** [comment]
@fly1chop 여기 이슈에서 브랜치 만든 뒤에 작업해주시면 좋을 것 같습니다~
